version: "3.3"

services:
        onestoptestnode:
                build:
                        context: .
                        dockerfile: Dockerfile.prod
                extra_hosts:
                        - "host.docker.internal:host-gateway"
                ports:
                        - "9015:9010"
                env_file:
                        - .env

volumes:
        onestopimages:
        onestopfiles:
